server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.166.37:3306/ebooksys?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ****
    password: *********
  servlet:
    multipart:
      max-file-size: 1000MB       # 设置单个文件最大大小为100MB
      max-request-size: 1000MB    # 设置多个文件大小为100MB



mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: /root/ebookshare/files/
    # path: D:\Desktop\files\
books:
  upload:
    path: /root/ebookshare/books/
    # path: D:\Desktop\books\
bookpic:
  upload:
    path: /root/ebookshare/books/bookcoverimage/
    # path: D:\Desktop\books\bookcoverimage\

auditbooks:
  upload:
    path: /root/ebookshare/auditbooks/
    # path: D:\Desktop\auditbooks\

auditbookpic:
  upload:
    path: /root/ebookshare/auditbooks/bookcoverimage/
    # path: D:\Desktop\auditbooks\bookcoverimage\

