name: Deploy

on:
  push:
    branches:
      - main # 当主分支代码提交的时候触发
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ebookshare:latest
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 在服务器上执行部署命令
            # 例如，停止现有容器，拉取最新的镜像，启动新容器等
            docker stop ebookshare || true
            docker rm ebookshare || true
            
            docker rmi ebookshare:latest || true
            
            # 拉取最新的镜像
            docker pull ebookshare:latest
            
            # 启动新容器
            docker run -d -p 9091:9090 --name ebookshare ebookshare:latest
    
